#!/usr/bin/env python3
"""Geocode talk addresses into ``_data/talk_locations.yml``.

For every ``address`` in ``_data/talks.yml`` that isn't already cached, this looks
up its coordinates via OpenStreetMap Nominatim and writes them to the cache file
(``address -> {lat, lon}``). The Talks page reads the cache to place map markers.

Runs automatically via a pre-commit hook on changes to ``_data/talks.yml``, or
manually:

    uv run --with pyyaml python scripts/geocode_talks.py

Only *uncached* addresses hit the network; if a lookup fails (e.g. offline) it warns
and exits 0 so it never blocks a commit — re-run later while online. Respects the
Nominatim usage policy (<=1 request/second, descriptive User-Agent).
"""

from __future__ import annotations

import json
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TALKS = ROOT / "_data" / "talks.yml"
CACHE = ROOT / "_data" / "talk_locations.yml"
NOMINATIM = "https://nominatim.openstreetmap.org/search"
USER_AGENT = "lampert.ai talks-map geocoder (+https://lampert.ai)"
HEADER = (
    "# Generated by scripts/geocode_talks.py — do not edit by hand.\n"
    "# Maps each talk `address` (from _data/talks.yml) to its coordinates.\n"
)


def load_yaml(path: Path):
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def geocode(address: str) -> dict | None:
    query = urllib.parse.urlencode({"q": address, "format": "json", "limit": 1})
    req = urllib.request.Request(
        f"{NOMINATIM}?{query}", headers={"User-Agent": USER_AGENT}
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        results = json.load(resp)
    if not results:
        return None
    return {
        "lat": round(float(results[0]["lat"]), 6),
        "lon": round(float(results[0]["lon"]), 6),
    }


def main() -> None:
    talks = load_yaml(TALKS) or []
    cache = load_yaml(CACHE) or {}

    addresses = []
    for talk in talks:
        address = (talk or {}).get("address")
        if address and address not in addresses:
            addresses.append(address)

    missing = [a for a in addresses if a not in cache]
    for i, address in enumerate(missing):
        if i:
            time.sleep(1)  # Nominatim: <= 1 request / second
        try:
            result = geocode(address)
        except Exception as exc:  # offline / rate-limited / etc. — never block.
            print(f"  geocode failed for {address!r}: {exc} (re-run online)", file=sys.stderr)
            continue
        if result:
            cache[address] = result
            print(f"  geocoded {address!r} -> {result['lat']}, {result['lon']}")
        else:
            print(f"  no result for {address!r}", file=sys.stderr)

    # Keep only addresses still in use, write only if something changed.
    cache = {a: cache[a] for a in addresses if a in cache}
    new_content = HEADER + yaml.safe_dump(
        cache, allow_unicode=True, sort_keys=True, default_flow_style=False
    )
    existing = CACHE.read_text(encoding="utf-8") if CACHE.exists() else ""
    if new_content != existing:
        CACHE.write_text(new_content, encoding="utf-8")
        print(f"  wrote {CACHE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
